platform :ios, '7.0'
pod 'pop', '~> 1.0.7'
pod 'AFNetworking', '~> 2.5.0'
pod 'MJPopupViewController', '~> 0.4'
pod 'Masonry', '~> 0.6.0'
pod 'LLSimpleCamera', '~> 2.1.1'
pod 'FMDB', '~> 2.5'
pod 'JSONKit', '~> 1.5pre'
pod 'MMDrawerController', '~> 0.5.7'
pod 'XHRealTimeBlur'
pod 'SDWebImage', '~> 3.7.2'
pod 'ReactiveCocoa'
pod 'MJRefresh', '~> 2.0.1'
